import { Fragment } from 'react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import '../styles/app.scss'

function MyApp({ Component, pageProps }: AppProps) {
  return (<Fragment>
    <Head>
      <title>DeX Tool</title>
      <meta name="description" content="The DeX Tool generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Component {...pageProps} />
    </main>
  </Fragment>)
}

export default MyApp
