import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, notification } from 'antd'
import styles from '../styles/Home.module.css'

const enum DEX_TYPES {
  U2 = 'Uniswap v2',
  U3 = 'Uniswap v3'
}

const openNotificationWithIcon = (type, title, description) => {
  notification[type]({ message: title, description });
};

const Home: NextPage = () => {
  const [ephemeral, setEphemeral] = useState({})

  const requestDexTrades = (type = 'U2') => {
    if (!Object.keys(DEX_TYPES).includes(type)) {
      openNotificationWithIcon('error', 'Something Wrong', 'Unsupported protocol is requested. Please check it again.')
      return;
    }
    requestUniswapTrades(type)
  }

  const requestUniswapTrades = (type) => {
    const protocol = DEX_TYPES[type]
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DeX Tool</title>
        <meta name="description" content="The DeX Tool generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">DeX Tools</a>
        </h1>

        <p className={styles.description}>
          Get started by clicking{' '}
          <Button type="primary" loading={ephemeral.u2} shape="round" size="large" onClick={() => {requestDexTrades('U2')}}>Uniswap v2</Button>
          {' '}or{' '}
          <Button type="primary" loading={ephemeral.u3} shape="round" size="large" onClick={() => {requestDexTrades('U4')}}>Uniswap v3</Button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
