import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'antd'
import styles from '../styles/Home.module.css'
import { DEX_PROTOCOLS } from '../common/enums/types'
import { openNotificationWithIcon } from '../common/utilities/notifications'
import { getUniSwapTrades } from '../common/api/bitquery'

const Home: NextPage = () => {
  const [ephemeral, setEphemeral] = useState({})
  const [trades, setTrades] = useState(null)

  useEffect(() => {
    console.log(trades)
  }, [trades])

  const requestDexTrades = (type) => {
    if (!type || !Object.keys(DEX_PROTOCOLS).includes(type)) {
      openNotificationWithIcon('error', 'Something Wrong', 'Unsupported protocol is requested. Please check it again.')
      return;
    }
    const protocol = DEX_PROTOCOLS[type]
    setEphemeral({ ...ephemeral, [type]: true })
    getUniSwapTrades(protocol).then(trds => {
      setEphemeral({ ...ephemeral, [type]: false })
      setTrades(trds)
    }, error => {
      setEphemeral({ ...ephemeral, [type]: false })
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DeX Tool</title>
        <meta name="description" content="The DeX Tool generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">DeX Tools</a>
        </h1>

        <p className={styles.description}>
          Get started by clicking{' '}
          <Button type="primary" loading={ephemeral.US2} shape="round" size="large" onClick={() => {requestDexTrades('US2')}}>Uniswap v2</Button>
          {' '}or{' '}
          <Button type="primary" loading={ephemeral.US3} shape="round" size="large" onClick={() => {requestDexTrades('US3')}}>Uniswap v3</Button>
          {' '}or{' '}
          <Button type="primary" loading={ephemeral.PS} shape="round" size="large" onClick={() => {requestDexTrades('PS')}} danger>PancakeSwap</Button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://bitquery.io/" target="_blank" rel="noopener noreferrer">
          Powered by BitQuery
        </a>
      </footer>
    </div>
  )
}

export default Home
